### ISSUE TITLE
Permettre de désactiver le saut avant de couler.

### ISSUE THREAD

**Issue by Maxs1789** [christopho/solarus#530]
Dans les zelda 'oracle', Si le héro ne peut pas nager, il coule dès qu'il va dans l'eau et n'effectue pas de saut avant.

Il faudrait pouvoir personnaliser le comportement du héro pour ce genre de chose.

**Comment by Diarandor** [comment]
I do not like that jump either.
I suggest to make an event hero:on_drown_started() to allow customization of what happens before the hero starts plunging on water without the swim hability. This could be used to remove the jump (and the jump sound), choose the "drown" animation we show, and also allows to choose if we remove or not some life from the hero and how much. If the event is nil, we would have the usual behaviour. (Also, an event hero:on_drown_finished() could be useful, for instance to choose the animation we show on the hero after he reappears in solid ground or what happens then.)

**Comment by Diarandor** [comment]
This feature is really important if we want to avoid the hero jumping over a 16x16 water tile, which could interfere with some important puzzles if we have not obtained neither the jump ability (roc's feather) nor the swimming ability. The jumping animation is not that important, the annoying thing is allowing to jump over a water tile. That is actually the problem I have, since this interferes completely with the mechanincs of my game.

This may happen if the hero does not have yet the swimming and jumping abilities and we use a water tile as a temporary obstacle which can be avoided later when the jumping or swimming ability is obtained.

In my game only one of the 3 main heroes will obtain the jumping ability, other of them will obtain the swimming ability, and the last one none of them, so I want to avoid the heroes to jump over a water tile, except the hero who can jump (and only in case we have already obtained the jump ability). I plan to use a row of water tiles as an obstacle for the third hero, but not for the other two (who can jump or swim, respectively,  over a 16x16 water tile after they obtain their ability, but not before).

**Comment by Diarandor** [comment]
> Dans les zelda 'oracle', Si le héro ne peut pas nager, il coule dès qu'il va dans l'eau et n'effectue pas de saut avant.

Il faudrait pouvoir personnaliser le comportement du héro pour ce genre de chose.

Ça n'as rien a voir avec le sujet, mais c'est rigolo, parce que j'ai trouvé ça:
> » héro
Abréviation familière de héroïne. 
Exemple : Il se drogue à l'héro.

» héros
Nom masculin qui désigne un personnage courageux ou important. Voir la définition de héros. 
Exemple : Le héros d'un film d'action.

**Comment by christopho** [comment]
An easy solution can be to add an ability "jump_over_water".

Otherwise, we need all these functions:

hero:start_plunging()
hero:start_back_to_solid_ground()
hero:on_entering_deep_water()
hero:on_drowning()

**Comment by Diarandor** [comment]
Maybe both things at the same time? 

I would stay with the easy solution for v1.5, since that is enough to solve the problem, and open a new issue (for v1.6 or later) for the functions, since they are not prioritary.

**Comment by Diarandor** [comment]
Or maybe just do the easy solution and forget about the functions (unless someone needs them)?

**Comment by christopho** [comment]
Let's do the "jump_over_water" for 1.5, and some of these functions for 1.6 because they can still be useful (#923).

**Comment by Diarandor** [comment]
Thanks! ^_^
