### ISSUE TITLE
OpenGl and Shader compilation

### ISSUE THREAD

**Issue by Nicolastriplec** [christopho/solarus#642]
Hi, I tried to compile the current version with opengl flag activate and I found some little compilation issues:

ShaderContext.cpp
std::unique_ptr<Shader> ShaderContext::create_shader(const std::string& /* shader_name */) {
uncoment parameter :dancer:
std::unique_ptr<Shader> ShaderContext::create_shader(const std::string& shader_name ) {

GL_2DShader.cpp and GL_2Dshader.h
void GL_2DShader::render(const SurfacePtr& /* quest_surface */)
miss const :dancer: 
void GL_2DShader::render(const SurfacePtr& /* quest_surface */) const

GL_ARBShader.cpp and GL_ARBShader.h
void GL_ARBShader::render(const SurfacePtr& quest_surface)
miss const :dancer:
void GL_ARBShader::render(const SurfacePtr& quest_surface) const

It is all! Oh! And congrats for this great job, I m allways following your progress :+1:

**Comment by christopho** [comment]
Thanks for the report. We will definetely fix the compilation issue, but you should know that the shader system is not finished yet, so there is no point in activating the OpenGL flag for now.

**Comment by Nicolastriplec** [comment]
I know it. I have been waiting the shader system for a long time. On the
other hand, is now running. What needs to be done yet?

2015-01-29 8:40 GMT+01:00 Christopho <notifications@github.com>:

**Comment by christopho** [comment]
@vlag ?

**Comment by vlag** [comment]
Shader system is indeed broken since the C++11 port, and since I'm still unable to build Solarus on OSX for now, I don't really know what should be fixed and when it will be.

Anyway, most of the work to consider it finished is to implement GLES shaders (and HLSL ones if possible), so maybe discuss a possible implementation of an abstraction library, like Angle (glsl to hlsl) or MojoShader (hlsl to glsl), which should ideally be optional at build part.

Another point is to discuss about parameters to share between the engine and shader scripts.
And finally, we have to choose how to handle shader files on quest side (still with one big file containing a table, a separate file for vertex shader, fragment shader and configuration ?).

However, shaders should already be ready to use for the OpenGL implementation, there are some filter and fun shaders here : https://github.com/christopho/solarus/issues/394

**Comment by Nicolastriplec** [comment]
Thanks for the answers!
Here comes my story: A time ago, I was testing these shaders in solarus 1.2
and the result was awesome! So I made my own shaders for my project based
in they :). In my quest there were also a time pass system. the temptation
was too strong.

So I tried porting the time variable internally into the engine and then
pass it to the shader and make a time engine's dynamic shader. And the
result was so cool. I will make a video for you. So I couldnt stop here,
and I implemented a primitive 2D light engine for the entities, hero
included... But well my code is very personal, not for share, and I make it
probably not by the best way.

However I tried to externalize my code to the max. If you want I could
upload the source for take a look. Maybe that motivate you.

2015-01-29 16:16 GMT+01:00 vlag <notifications@github.com>:

**Comment by christopho** [comment]
I have to admit I did not know that shaders ever worked in Solarus, I thought it always was a work in progress. I would love to see a video to better understand what can be done with them ! :)

**Comment by vlag** [comment]
@christopho : You can even test it directly, you just have to compile with OpenGL support and place shader files into the data/shaders/videomodes/ quest folder (hardware videomode are still dynamic for now, you don't have to edit any configuration file to be able to select them, it's another point to discuss but to be honest I really like this behavior :) )
In case, the xBR-hybrid-v5 smoothing shader is very impressive !
But indeed, a shader is just a script that can deal with pixel, so it is very very flexible, just like any scripting language :)

@Nicolastriplec I woud indeed be very interrested in seeing your shader, it seems very interesting :)
Just in case, the time elapsed since the current shader has started is already a variable shared between the engine and shader scripts, you can access it though
uniform int solarus_display_time;
Other shared variable are the SDL texture and the quest size.

**Comment by Nicolastriplec** [comment]
Ok boys! Here comes :)
https://www.youtube.com/watch?v=1cpJ6q9ppuE

2015-01-30 9:21 GMT+01:00 vlag <notifications@github.com>:

**Comment by wrightmat** [comment]
That is amazing!!! I need that point light functionality for my game - any chance you'll release the code for that shader?

**Comment by Nicolastriplec** [comment]
As you can see, I pass the hud layer and the map layer separate to the render, I will check if I can do the same with the map layers to apply different effects, maybe it is posible to generate a normal map in game for a map layer? @vlag?

**Comment by vlag** [comment]
Sorry I'm late, my MacBook is currently dying :)


Yeah, indeed impressive :)
Just to be sure, what are the effects of the video related to a shader ?

About specific effects, it depends on what you call a normal map. My notion of a normal map is a 3D area converted into a 2D grayscale image, but I'm not sure that it's what you were talking about.

Actually, if you pass the HUD and map layer separately to the render, I guess that you have changed some piece of code onto the engine, because for now I only implemented the "videomode" shader notion.
I have planned to add effects too (that's also why the path to access shaders into the quest is shaders/videomodes, I wish to add shaders/effects :) ), but since there are even more point to discuss than videomode shaders, I firstly want to finish this mecanism to have a strong foundation to be able to face the next part.

So it is technically possible, I'm not sure that a stable release of the system will be released soon.


To finish, I also made a video of current Solarus shaders, where most are ported ones from bsnes, mari0 and libretro.
Here is [the video](https://www.youtube.com/watch?v=eN5U07vwiYQ), [related shaders](https://github.com/christopho/solarus/issues/394), and the [OSX 1.3.1 Solarus engine, built with shader support and embedding zsdx quest with current ported shaders](https://dl.dropboxusercontent.com/u/31755496/solarus_packages/Solarus_1.3.1_Shaders.zip).

**Comment by Nicolastriplec** [comment]
Well in the first place this is 2D normal mapping
https://github.com/mattdesl/lwjgl-basics/wiki/ShaderLesson6,
http://mattdesl.github.io/kami-demos/release/normals-pixel.html
Then we have this:
http://stackoverflow.com/questions/2368728/can-normal-maps-be-generated-from-a-texture,
tecnically we can generate a normal map in runtime with the sobel operator
for a texture (2D surface) in addition we can make static normal maps for
sprites.

Actually I use a rudimentary 2D point lightning system without normal
mapping, I also use a color filter to be elements outlined in the dark. I
also use the color filter with a far away point light for the day light and
colors. Then moreover I use scripts for another effects, I have 2 layers of
clouds with sprites generated by lua and in the night I use a different
titleset. But I m not using surfice color filters for the day color
effects, it is in the shader engine. I was using alpha surfices in the past
and the result was poor.
Yes I modify some pieces of code into the engine, this was necesary to use
light points and day time variables on the render. and by the way to pass
the hud and the map layer separately. I think that in the future for a more
amazing shader system (like 2D normal mapping for example) it will be
necesary to pass every map layer separately to the render.
Actually I have a problem when the user change a map zone in overworld
becouse I lose the light point reference, For the moment I have to stop
rendering point lights until you are in another map. I m trying to emulate
the map movement when it go out.


2015-02-15 9:24 GMT+01:00 vlag <notifications@github.com>:

**Comment by wrightmat** [comment]
Has there been any more development on this? I'm really interested in this functionality and would be willing to help in any way I can. @Nicolastriplec, any chance you'd share your engine modifications with @Christopho so this functionality could be more quickly implemented into Solarus? It sounds like between your rendering modifications and @vlag's work on shaders, we could have some awesome effects!

**Comment by christopho** [comment]
I have no time for such a big work now, I am mostly working on games. The 1.4 release was huge and games did not make any progress for a long time. So for solarus and solarus-quest-editor, my priority is to fix bugs (especially crashes). I am still keeping a few new features for 1.5, but I have to make choices. Any help on shaders would be appreciated.

**Comment by vlag** [comment]
@christopho Again, you're the Solarus master, so even if you don't work on this feature, you're still the one that can guide us to the best way to implement shaders into the engine with the most constistency and flexibility for users possible.

For me and since the begginning, there are three main subject to clarify before going further with the shader system, else it might have a lot of revert/rewrite and I don't wish that again ;) : 
* Implement GLES and HLSL, or discuss about implementing an abstraction shader feature (probably a third party lib).
* Parameters to share between engine and shader scripts (or make the shader class exportable to lua to let the decision to quest makers ?).
* How to handle shader files and structure (keep one big lua file or separate into 3 files, make shader class exportable to lua, still list shader files dynamically ?).

There is also a good point on the other issue, about how to pass Textures to the renderer (one render by layer, to allow a different shader by layer, or still one render for the whole frame) ?

**Comment by christopho** [comment]
There are a lot of huge and very interesting issues, and let's admit it, it is not realistic to do them all for 1.5. Zelda Mercuris' Chest did not make any significant progress since Solarus 1.0, contrary to Solarus and Solarus Quest Editor that had tons of improvements and new features.

Rather than keeping all issues planned for 1.5, and continuing to postpone their milestone at each release (some issues were postponed like this since 1.2), I made a pass on all issues and kept 1.5 for the ones we really intend to finish before 1.5.

Now about shaders, I can't give answers to your questions now, their design in Solarus is a fundamental question that I am not expert enough to answer yet. But this issue is supposed to be about a compilation problem, right? Let's discuss shaders in the correct place, #394.
