### ISSUE TITLE
Crash when changing sprite animation

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#705]
After the crash, the error.txt file says "Fatal: This sprite does not belong to this entity".

I am not sure at all what is producing the crash, but I think it happens when using the method sprite:set_animation(...) after calling the method sprite:fade_out(). I am using the sprite of an enemy entity.

(I have already sent the data to Christopho via dropbox.)

**Comment by christopho** [comment]
@Diarandor I don't have your data or I don't know how to access them, maybe I have problems with dropbox. It is possible to host the data to google drive instead?
And I need accurate information to be able to reproduce the crash. Thanks

**Comment by Diarandor** [comment]
Ok, I will put it on google drive and send you a link.

**Comment by christopho** [comment]
Fixed in 1.4.3.

There is an error in your chameleon script: you call enemy:remove_sprite(tongue) several times, because the "if tongue then" condition remains true. I think you forgot to set tongue to nil after you removed it.
So the sprite still exists in your Lua script, but no longer belongs to the enemy, which leads to an error message.
Before 1.4.3, the program crashes after the error, after 1.4.3 it will show a normal error message and continue:

    Error: In on_animation_finished: [string "enemies/animals/chameleon.lua"]:83: bad argument #1 to remove_sprite (This sprite does not belong to this entity)

**Comment by Diarandor** [comment]
You are right. Thank you! The script works fine now.
