### ISSUE TITLE
Possible bugs with circle movement

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#721]
In the Lua API it says that the functions get_angle_speed() and set_angle_speed() of circle movements are given in radians per second. But, if I am not wrong, they are given in degrees per second. (So, either we should change the Lua API, or we should fix this.) 

I also have problems with the function set_initial_angle(), that does not admit values out of the range [0, 2*pi), if I am not wrong. For example, set_initial_angle(10) gives the error "Invalid initial angle: 10". (Also, if I write set_initial_angle(math.pi/2), it does not start with 90 degrees angle.)

I have not checked the rest of functions of the circle movement, so there could be more bugs.

**Comment by Diarandor** [comment]
I have checked the C++ file for the circle movement, and I confirm that it is missing the conversion of the input angle from radians to degrees in the functions:
```
void CircleMovement::set_angle_speed
int CircleMovement::get_angle_speed() const
```
(It would be nice to set a max angle speed, to avoid a crash.) The initial angle is not working, it starts always with zero angle.

**Comment by Morwenn** [comment]
Just as a side note, it would be easy to solve most of units problems on the C++ side using [Boost.Units](http://www.boost.org/doc/libs/1_58_0/doc/html/boost_units/Units.html) to check at compile-time whether the units we are using are consistent. That said, we can't transfer the type system to Lua, so that would solve only hlaf of the problem. Boost.Units also includes an "angle" unit - whatever it means - to prevent exactly the degrees/radians problem.
