### ISSUE TITLE
Enhancement: sprite animation of brandished item only shows first frame.

### ISSUE THREAD

**Issue by Diarandor** [christopho/solarus#790]
I created a pickable item that is brandished when obtained and its animation has several frames. The sprite animation of the pickable is the same used when brandishing the item. When the hero brandish the treasure, only the first frame is shown, because the map is suspended (so the sprite animation is paused). 

I think that the suspension of the map should not affect the sprite animation of the brandished item.

I tried to use the following workaround
```
pickable:get_sprite():set_ignore_suspend(true)
```
in the map script, but it does not work (the sprite of the pickable is not being used in the brandishing animation).

There is no possible workaround since there is no function to get  the sprite of the brandished item.

**Comment by christopho** [comment]
This is now fixed in 1.5 development version. Now, brandished treasures and shop treasures are correctly animated.

Unfortunately, this creates a slight surprise for animated item sprites that are assuming that they always stay on the first frame when used in a brandished treasure or a shop treasure. In my project, this was the case of hearts. Since I don't want the falling heart animation when a heart is brandished or in a heart shop treasure, I fixed the heart sprite animation to only have one frame, and for pickable hearts I set another animation. In short, you probably need to do this in your project if you use the same heart script and sprite as me: https://github.com/christopho/zsdx/commit/562964712b2da6b26e84d393e870c23cccb7335e
